name: CI

on:
  push:
    branches:
      - 'master'
      - 'renovate/*'
      - 'release/*'
      - 'ci/*'
  pull_request:
    branches:
      - '*'
      - '!translations'
      - '!renovate/*'
      - '!release/*'
      - '!ci/*'
    types: [assigned, opened, synchronize, reopened]

jobs:
  test:
    name: Run tests on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    if: "!contains(github.event.head_commit.message, 'ci skip')"

    strategy:
      matrix:
        node_version: [16.x]
        os: [windows-latest, macOS-latest]

    steps:
      - name: set git config
        run: |
          git config --global core.eol lf
          git config --global core.autocrlf false

      - uses: actions/checkout@v1

      - name: setup nodejs
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}

      - name: install yarn
        run: npm install -g yarn

      - name: get yarn cache dir
        id: yarn-cache-dir
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v1
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: install dependencies
        run: yarn

      - name: electron build
        run: yarn release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
